/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as CoursesCourseRouteImport } from './routes/courses/$course'
import { Route as AdminDashboardLayoutRouteImport } from './routes/admin/_dashboardLayout'
import { Route as AdminAuthRouteImport } from './routes/admin/_auth'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as userDashboardDashboardLayoutRouteImport } from './routes/(userDashboard)/_dashboardLayout'
import { Route as AdminAuthSignupRouteImport } from './routes/admin/_auth/signup'
import { Route as AdminAuthLoginRouteImport } from './routes/admin/_auth/login'
import { Route as AdminDashboardLayoutDashboardIndexRouteImport } from './routes/admin/_dashboardLayout/dashboard/index'
import { Route as userDashboardDashboardLayoutDashboardIndexRouteImport } from './routes/(userDashboard)/_dashboardLayout/dashboard/index'
import { Route as AdminDashboardLayoutDashboardUsersRouteImport } from './routes/admin/_dashboardLayout/dashboard/users'
import { Route as AdminDashboardLayoutDashboardSettingsRouteImport } from './routes/admin/_dashboardLayout/dashboard/settings'
import { Route as userDashboardDashboardLayoutDashboardSettingsRouteImport } from './routes/(userDashboard)/_dashboardLayout/dashboard/settings'
import { Route as userDashboardDashboardLayoutDashboardSearchRouteImport } from './routes/(userDashboard)/_dashboardLayout/dashboard/search'
import { Route as userDashboardDashboardLayoutDashboardProfileRouteImport } from './routes/(userDashboard)/_dashboardLayout/dashboard/profile'
import { Route as userDashboardDashboardLayoutDashboardNotificationsRouteImport } from './routes/(userDashboard)/_dashboardLayout/dashboard/notifications'
import { Route as userDashboardDashboardLayoutDashboardMentorRouteImport } from './routes/(userDashboard)/_dashboardLayout/dashboard/mentor'
import { Route as userDashboardDashboardLayoutDashboardLeaderboardRouteImport } from './routes/(userDashboard)/_dashboardLayout/dashboard/leaderboard'
import { Route as AdminDashboardLayoutDashboardQuizzesManagementIndexRouteImport } from './routes/admin/_dashboardLayout/dashboard/quizzes-management/index'
import { Route as AdminDashboardLayoutDashboardCourseManagementIndexRouteImport } from './routes/admin/_dashboardLayout/dashboard/course-management/index'
import { Route as userDashboardDashboardLayoutDashboardQuizzesIndexRouteImport } from './routes/(userDashboard)/_dashboardLayout/dashboard/quizzes/index'
import { Route as userDashboardDashboardLayoutDashboardMyCoursesIndexRouteImport } from './routes/(userDashboard)/_dashboardLayout/dashboard/my-courses/index'
import { Route as AdminDashboardLayoutDashboardCourseManagementTableDataRouteImport } from './routes/admin/_dashboardLayout/dashboard/course-management/TableData'
import { Route as userDashboardDashboardLayoutDashboardQuizzesIdRouteImport } from './routes/(userDashboard)/_dashboardLayout/dashboard/quizzes/$id'
import { Route as AdminDashboardLayoutDashboardQuizzesManagementPreviewIndexRouteImport } from './routes/admin/_dashboardLayout/dashboard/quizzes-management/preview/index'
import { Route as AdminDashboardLayoutDashboardQuizzesManagementNewQuizIndexRouteImport } from './routes/admin/_dashboardLayout/dashboard/quizzes-management/new-quiz/index'
import { Route as AdminDashboardLayoutDashboardQuizzesManagementNewQuizLecIndexRouteImport } from './routes/admin/_dashboardLayout/dashboard/quizzes-management/new-quiz-lec/index'
import { Route as AdminDashboardLayoutDashboardCourseManagementPreviewCoursesIndexRouteImport } from './routes/admin/_dashboardLayout/dashboard/course-management/preview-courses/index'
import { Route as AdminDashboardLayoutDashboardCourseManagementNewCourseIndexRouteImport } from './routes/admin/_dashboardLayout/dashboard/course-management/new-course/index'
import { Route as AdminDashboardLayoutDashboardCourseManagementNewCourseLecIndexRouteImport } from './routes/admin/_dashboardLayout/dashboard/course-management/new-course-lec/index'
import { Route as userDashboardDashboardLayoutDashboardMyCoursesIdIndexRouteImport } from './routes/(userDashboard)/_dashboardLayout/dashboard/my-courses/$id/index'
import { Route as userDashboardDashboardLayoutDashboardMyCoursesIdLearnLectureLectureidRouteImport } from './routes/(userDashboard)/_dashboardLayout/dashboard/my-courses/$id/learn/lecture/$lectureid'

const AdminRouteImport = createFileRoute('/admin')()
const userDashboardRouteImport = createFileRoute('/(userDashboard)')()
const IndexLazyRouteImport = createFileRoute('/')()

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const userDashboardRoute = userDashboardRouteImport.update({
  id: '/(userDashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseRoute = CoursesCourseRouteImport.update({
  id: '/courses/$course',
  path: '/courses/$course',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardLayoutRoute = AdminDashboardLayoutRouteImport.update({
  id: '/_dashboardLayout',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => AdminRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const userDashboardDashboardLayoutRoute =
  userDashboardDashboardLayoutRouteImport.update({
    id: '/_dashboardLayout',
    getParentRoute: () => userDashboardRoute,
  } as any)
const AdminAuthSignupRoute = AdminAuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthLoginRoute = AdminAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminDashboardLayoutDashboardIndexRoute =
  AdminDashboardLayoutDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AdminDashboardLayoutRoute,
  } as any)
const userDashboardDashboardLayoutDashboardIndexRoute =
  userDashboardDashboardLayoutDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => userDashboardDashboardLayoutRoute,
  } as any)
const AdminDashboardLayoutDashboardUsersRoute =
  AdminDashboardLayoutDashboardUsersRouteImport.update({
    id: '/dashboard/users',
    path: '/dashboard/users',
    getParentRoute: () => AdminDashboardLayoutRoute,
  } as any)
const AdminDashboardLayoutDashboardSettingsRoute =
  AdminDashboardLayoutDashboardSettingsRouteImport.update({
    id: '/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => AdminDashboardLayoutRoute,
  } as any)
const userDashboardDashboardLayoutDashboardSettingsRoute =
  userDashboardDashboardLayoutDashboardSettingsRouteImport.update({
    id: '/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => userDashboardDashboardLayoutRoute,
  } as any)
const userDashboardDashboardLayoutDashboardSearchRoute =
  userDashboardDashboardLayoutDashboardSearchRouteImport.update({
    id: '/dashboard/search',
    path: '/dashboard/search',
    getParentRoute: () => userDashboardDashboardLayoutRoute,
  } as any)
const userDashboardDashboardLayoutDashboardProfileRoute =
  userDashboardDashboardLayoutDashboardProfileRouteImport.update({
    id: '/dashboard/profile',
    path: '/dashboard/profile',
    getParentRoute: () => userDashboardDashboardLayoutRoute,
  } as any)
const userDashboardDashboardLayoutDashboardNotificationsRoute =
  userDashboardDashboardLayoutDashboardNotificationsRouteImport.update({
    id: '/dashboard/notifications',
    path: '/dashboard/notifications',
    getParentRoute: () => userDashboardDashboardLayoutRoute,
  } as any)
const userDashboardDashboardLayoutDashboardMentorRoute =
  userDashboardDashboardLayoutDashboardMentorRouteImport.update({
    id: '/dashboard/mentor',
    path: '/dashboard/mentor',
    getParentRoute: () => userDashboardDashboardLayoutRoute,
  } as any)
const userDashboardDashboardLayoutDashboardLeaderboardRoute =
  userDashboardDashboardLayoutDashboardLeaderboardRouteImport.update({
    id: '/dashboard/leaderboard',
    path: '/dashboard/leaderboard',
    getParentRoute: () => userDashboardDashboardLayoutRoute,
  } as any)
const AdminDashboardLayoutDashboardQuizzesManagementIndexRoute =
  AdminDashboardLayoutDashboardQuizzesManagementIndexRouteImport.update({
    id: '/dashboard/quizzes-management/',
    path: '/dashboard/quizzes-management/',
    getParentRoute: () => AdminDashboardLayoutRoute,
  } as any)
const AdminDashboardLayoutDashboardCourseManagementIndexRoute =
  AdminDashboardLayoutDashboardCourseManagementIndexRouteImport.update({
    id: '/dashboard/course-management/',
    path: '/dashboard/course-management/',
    getParentRoute: () => AdminDashboardLayoutRoute,
  } as any)
const userDashboardDashboardLayoutDashboardQuizzesIndexRoute =
  userDashboardDashboardLayoutDashboardQuizzesIndexRouteImport.update({
    id: '/dashboard/quizzes/',
    path: '/dashboard/quizzes/',
    getParentRoute: () => userDashboardDashboardLayoutRoute,
  } as any)
const userDashboardDashboardLayoutDashboardMyCoursesIndexRoute =
  userDashboardDashboardLayoutDashboardMyCoursesIndexRouteImport.update({
    id: '/dashboard/my-courses/',
    path: '/dashboard/my-courses/',
    getParentRoute: () => userDashboardDashboardLayoutRoute,
  } as any)
const AdminDashboardLayoutDashboardCourseManagementTableDataRoute =
  AdminDashboardLayoutDashboardCourseManagementTableDataRouteImport.update({
    id: '/dashboard/course-management/TableData',
    path: '/dashboard/course-management/TableData',
    getParentRoute: () => AdminDashboardLayoutRoute,
  } as any)
const userDashboardDashboardLayoutDashboardQuizzesIdRoute =
  userDashboardDashboardLayoutDashboardQuizzesIdRouteImport.update({
    id: '/dashboard/quizzes/$id',
    path: '/dashboard/quizzes/$id',
    getParentRoute: () => userDashboardDashboardLayoutRoute,
  } as any)
const AdminDashboardLayoutDashboardQuizzesManagementPreviewIndexRoute =
  AdminDashboardLayoutDashboardQuizzesManagementPreviewIndexRouteImport.update({
    id: '/dashboard/quizzes-management/preview/',
    path: '/dashboard/quizzes-management/preview/',
    getParentRoute: () => AdminDashboardLayoutRoute,
  } as any)
const AdminDashboardLayoutDashboardQuizzesManagementNewQuizIndexRoute =
  AdminDashboardLayoutDashboardQuizzesManagementNewQuizIndexRouteImport.update({
    id: '/dashboard/quizzes-management/new-quiz/',
    path: '/dashboard/quizzes-management/new-quiz/',
    getParentRoute: () => AdminDashboardLayoutRoute,
  } as any)
const AdminDashboardLayoutDashboardQuizzesManagementNewQuizLecIndexRoute =
  AdminDashboardLayoutDashboardQuizzesManagementNewQuizLecIndexRouteImport.update(
    {
      id: '/dashboard/quizzes-management/new-quiz-lec/',
      path: '/dashboard/quizzes-management/new-quiz-lec/',
      getParentRoute: () => AdminDashboardLayoutRoute,
    } as any,
  )
const AdminDashboardLayoutDashboardCourseManagementPreviewCoursesIndexRoute =
  AdminDashboardLayoutDashboardCourseManagementPreviewCoursesIndexRouteImport.update(
    {
      id: '/dashboard/course-management/preview-courses/',
      path: '/dashboard/course-management/preview-courses/',
      getParentRoute: () => AdminDashboardLayoutRoute,
    } as any,
  )
const AdminDashboardLayoutDashboardCourseManagementNewCourseIndexRoute =
  AdminDashboardLayoutDashboardCourseManagementNewCourseIndexRouteImport.update(
    {
      id: '/dashboard/course-management/new-course/',
      path: '/dashboard/course-management/new-course/',
      getParentRoute: () => AdminDashboardLayoutRoute,
    } as any,
  )
const AdminDashboardLayoutDashboardCourseManagementNewCourseLecIndexRoute =
  AdminDashboardLayoutDashboardCourseManagementNewCourseLecIndexRouteImport.update(
    {
      id: '/dashboard/course-management/new-course-lec/',
      path: '/dashboard/course-management/new-course-lec/',
      getParentRoute: () => AdminDashboardLayoutRoute,
    } as any,
  )
const userDashboardDashboardLayoutDashboardMyCoursesIdIndexRoute =
  userDashboardDashboardLayoutDashboardMyCoursesIdIndexRouteImport.update({
    id: '/dashboard/my-courses/$id/',
    path: '/dashboard/my-courses/$id/',
    getParentRoute: () => userDashboardDashboardLayoutRoute,
  } as any)
const userDashboardDashboardLayoutDashboardMyCoursesIdLearnLectureLectureidRoute =
  userDashboardDashboardLayoutDashboardMyCoursesIdLearnLectureLectureidRouteImport.update(
    {
      id: '/dashboard/my-courses/$id/learn/lecture/$lectureid',
      path: '/dashboard/my-courses/$id/learn/lecture/$lectureid',
      getParentRoute: () => userDashboardDashboardLayoutRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof userDashboardDashboardLayoutRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/pricing': typeof PricingRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/admin': typeof AdminDashboardLayoutRouteWithChildren
  '/courses/$course': typeof CoursesCourseRoute
  '/courses': typeof CoursesIndexRoute
  '/admin/login': typeof AdminAuthLoginRoute
  '/admin/signup': typeof AdminAuthSignupRoute
  '/dashboard/leaderboard': typeof userDashboardDashboardLayoutDashboardLeaderboardRoute
  '/dashboard/mentor': typeof userDashboardDashboardLayoutDashboardMentorRoute
  '/dashboard/notifications': typeof userDashboardDashboardLayoutDashboardNotificationsRoute
  '/dashboard/profile': typeof userDashboardDashboardLayoutDashboardProfileRoute
  '/dashboard/search': typeof userDashboardDashboardLayoutDashboardSearchRoute
  '/dashboard/settings': typeof userDashboardDashboardLayoutDashboardSettingsRoute
  '/admin/dashboard/settings': typeof AdminDashboardLayoutDashboardSettingsRoute
  '/admin/dashboard/users': typeof AdminDashboardLayoutDashboardUsersRoute
  '/dashboard': typeof userDashboardDashboardLayoutDashboardIndexRoute
  '/admin/dashboard': typeof AdminDashboardLayoutDashboardIndexRoute
  '/dashboard/quizzes/$id': typeof userDashboardDashboardLayoutDashboardQuizzesIdRoute
  '/admin/dashboard/course-management/TableData': typeof AdminDashboardLayoutDashboardCourseManagementTableDataRoute
  '/dashboard/my-courses': typeof userDashboardDashboardLayoutDashboardMyCoursesIndexRoute
  '/dashboard/quizzes': typeof userDashboardDashboardLayoutDashboardQuizzesIndexRoute
  '/admin/dashboard/course-management': typeof AdminDashboardLayoutDashboardCourseManagementIndexRoute
  '/admin/dashboard/quizzes-management': typeof AdminDashboardLayoutDashboardQuizzesManagementIndexRoute
  '/dashboard/my-courses/$id': typeof userDashboardDashboardLayoutDashboardMyCoursesIdIndexRoute
  '/admin/dashboard/course-management/new-course-lec': typeof AdminDashboardLayoutDashboardCourseManagementNewCourseLecIndexRoute
  '/admin/dashboard/course-management/new-course': typeof AdminDashboardLayoutDashboardCourseManagementNewCourseIndexRoute
  '/admin/dashboard/course-management/preview-courses': typeof AdminDashboardLayoutDashboardCourseManagementPreviewCoursesIndexRoute
  '/admin/dashboard/quizzes-management/new-quiz-lec': typeof AdminDashboardLayoutDashboardQuizzesManagementNewQuizLecIndexRoute
  '/admin/dashboard/quizzes-management/new-quiz': typeof AdminDashboardLayoutDashboardQuizzesManagementNewQuizIndexRoute
  '/admin/dashboard/quizzes-management/preview': typeof AdminDashboardLayoutDashboardQuizzesManagementPreviewIndexRoute
  '/dashboard/my-courses/$id/learn/lecture/$lectureid': typeof userDashboardDashboardLayoutDashboardMyCoursesIdLearnLectureLectureidRoute
}
export interface FileRoutesByTo {
  '/': typeof userDashboardDashboardLayoutRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/pricing': typeof PricingRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/admin': typeof AdminDashboardLayoutRouteWithChildren
  '/courses/$course': typeof CoursesCourseRoute
  '/courses': typeof CoursesIndexRoute
  '/admin/login': typeof AdminAuthLoginRoute
  '/admin/signup': typeof AdminAuthSignupRoute
  '/dashboard/leaderboard': typeof userDashboardDashboardLayoutDashboardLeaderboardRoute
  '/dashboard/mentor': typeof userDashboardDashboardLayoutDashboardMentorRoute
  '/dashboard/notifications': typeof userDashboardDashboardLayoutDashboardNotificationsRoute
  '/dashboard/profile': typeof userDashboardDashboardLayoutDashboardProfileRoute
  '/dashboard/search': typeof userDashboardDashboardLayoutDashboardSearchRoute
  '/dashboard/settings': typeof userDashboardDashboardLayoutDashboardSettingsRoute
  '/admin/dashboard/settings': typeof AdminDashboardLayoutDashboardSettingsRoute
  '/admin/dashboard/users': typeof AdminDashboardLayoutDashboardUsersRoute
  '/dashboard': typeof userDashboardDashboardLayoutDashboardIndexRoute
  '/admin/dashboard': typeof AdminDashboardLayoutDashboardIndexRoute
  '/dashboard/quizzes/$id': typeof userDashboardDashboardLayoutDashboardQuizzesIdRoute
  '/admin/dashboard/course-management/TableData': typeof AdminDashboardLayoutDashboardCourseManagementTableDataRoute
  '/dashboard/my-courses': typeof userDashboardDashboardLayoutDashboardMyCoursesIndexRoute
  '/dashboard/quizzes': typeof userDashboardDashboardLayoutDashboardQuizzesIndexRoute
  '/admin/dashboard/course-management': typeof AdminDashboardLayoutDashboardCourseManagementIndexRoute
  '/admin/dashboard/quizzes-management': typeof AdminDashboardLayoutDashboardQuizzesManagementIndexRoute
  '/dashboard/my-courses/$id': typeof userDashboardDashboardLayoutDashboardMyCoursesIdIndexRoute
  '/admin/dashboard/course-management/new-course-lec': typeof AdminDashboardLayoutDashboardCourseManagementNewCourseLecIndexRoute
  '/admin/dashboard/course-management/new-course': typeof AdminDashboardLayoutDashboardCourseManagementNewCourseIndexRoute
  '/admin/dashboard/course-management/preview-courses': typeof AdminDashboardLayoutDashboardCourseManagementPreviewCoursesIndexRoute
  '/admin/dashboard/quizzes-management/new-quiz-lec': typeof AdminDashboardLayoutDashboardQuizzesManagementNewQuizLecIndexRoute
  '/admin/dashboard/quizzes-management/new-quiz': typeof AdminDashboardLayoutDashboardQuizzesManagementNewQuizIndexRoute
  '/admin/dashboard/quizzes-management/preview': typeof AdminDashboardLayoutDashboardQuizzesManagementPreviewIndexRoute
  '/dashboard/my-courses/$id/learn/lecture/$lectureid': typeof userDashboardDashboardLayoutDashboardMyCoursesIdLearnLectureLectureidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/_auth': typeof AuthRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/pricing': typeof PricingRoute
  '/(userDashboard)': typeof userDashboardRouteWithChildren
  '/(userDashboard)/_dashboardLayout': typeof userDashboardDashboardLayoutRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/_auth': typeof AdminAuthRouteWithChildren
  '/admin/_dashboardLayout': typeof AdminDashboardLayoutRouteWithChildren
  '/courses/$course': typeof CoursesCourseRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/_auth/login': typeof AdminAuthLoginRoute
  '/admin/_auth/signup': typeof AdminAuthSignupRoute
  '/(userDashboard)/_dashboardLayout/dashboard/leaderboard': typeof userDashboardDashboardLayoutDashboardLeaderboardRoute
  '/(userDashboard)/_dashboardLayout/dashboard/mentor': typeof userDashboardDashboardLayoutDashboardMentorRoute
  '/(userDashboard)/_dashboardLayout/dashboard/notifications': typeof userDashboardDashboardLayoutDashboardNotificationsRoute
  '/(userDashboard)/_dashboardLayout/dashboard/profile': typeof userDashboardDashboardLayoutDashboardProfileRoute
  '/(userDashboard)/_dashboardLayout/dashboard/search': typeof userDashboardDashboardLayoutDashboardSearchRoute
  '/(userDashboard)/_dashboardLayout/dashboard/settings': typeof userDashboardDashboardLayoutDashboardSettingsRoute
  '/admin/_dashboardLayout/dashboard/settings': typeof AdminDashboardLayoutDashboardSettingsRoute
  '/admin/_dashboardLayout/dashboard/users': typeof AdminDashboardLayoutDashboardUsersRoute
  '/(userDashboard)/_dashboardLayout/dashboard/': typeof userDashboardDashboardLayoutDashboardIndexRoute
  '/admin/_dashboardLayout/dashboard/': typeof AdminDashboardLayoutDashboardIndexRoute
  '/(userDashboard)/_dashboardLayout/dashboard/quizzes/$id': typeof userDashboardDashboardLayoutDashboardQuizzesIdRoute
  '/admin/_dashboardLayout/dashboard/course-management/TableData': typeof AdminDashboardLayoutDashboardCourseManagementTableDataRoute
  '/(userDashboard)/_dashboardLayout/dashboard/my-courses/': typeof userDashboardDashboardLayoutDashboardMyCoursesIndexRoute
  '/(userDashboard)/_dashboardLayout/dashboard/quizzes/': typeof userDashboardDashboardLayoutDashboardQuizzesIndexRoute
  '/admin/_dashboardLayout/dashboard/course-management/': typeof AdminDashboardLayoutDashboardCourseManagementIndexRoute
  '/admin/_dashboardLayout/dashboard/quizzes-management/': typeof AdminDashboardLayoutDashboardQuizzesManagementIndexRoute
  '/(userDashboard)/_dashboardLayout/dashboard/my-courses/$id/': typeof userDashboardDashboardLayoutDashboardMyCoursesIdIndexRoute
  '/admin/_dashboardLayout/dashboard/course-management/new-course-lec/': typeof AdminDashboardLayoutDashboardCourseManagementNewCourseLecIndexRoute
  '/admin/_dashboardLayout/dashboard/course-management/new-course/': typeof AdminDashboardLayoutDashboardCourseManagementNewCourseIndexRoute
  '/admin/_dashboardLayout/dashboard/course-management/preview-courses/': typeof AdminDashboardLayoutDashboardCourseManagementPreviewCoursesIndexRoute
  '/admin/_dashboardLayout/dashboard/quizzes-management/new-quiz-lec/': typeof AdminDashboardLayoutDashboardQuizzesManagementNewQuizLecIndexRoute
  '/admin/_dashboardLayout/dashboard/quizzes-management/new-quiz/': typeof AdminDashboardLayoutDashboardQuizzesManagementNewQuizIndexRoute
  '/admin/_dashboardLayout/dashboard/quizzes-management/preview/': typeof AdminDashboardLayoutDashboardQuizzesManagementPreviewIndexRoute
  '/(userDashboard)/_dashboardLayout/dashboard/my-courses/$id/learn/lecture/$lectureid': typeof userDashboardDashboardLayoutDashboardMyCoursesIdLearnLectureLectureidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/pricing'
    | '/login'
    | '/signup'
    | '/admin'
    | '/courses/$course'
    | '/courses'
    | '/admin/login'
    | '/admin/signup'
    | '/dashboard/leaderboard'
    | '/dashboard/mentor'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/search'
    | '/dashboard/settings'
    | '/admin/dashboard/settings'
    | '/admin/dashboard/users'
    | '/dashboard'
    | '/admin/dashboard'
    | '/dashboard/quizzes/$id'
    | '/admin/dashboard/course-management/TableData'
    | '/dashboard/my-courses'
    | '/dashboard/quizzes'
    | '/admin/dashboard/course-management'
    | '/admin/dashboard/quizzes-management'
    | '/dashboard/my-courses/$id'
    | '/admin/dashboard/course-management/new-course-lec'
    | '/admin/dashboard/course-management/new-course'
    | '/admin/dashboard/course-management/preview-courses'
    | '/admin/dashboard/quizzes-management/new-quiz-lec'
    | '/admin/dashboard/quizzes-management/new-quiz'
    | '/admin/dashboard/quizzes-management/preview'
    | '/dashboard/my-courses/$id/learn/lecture/$lectureid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/pricing'
    | '/login'
    | '/signup'
    | '/admin'
    | '/courses/$course'
    | '/courses'
    | '/admin/login'
    | '/admin/signup'
    | '/dashboard/leaderboard'
    | '/dashboard/mentor'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/search'
    | '/dashboard/settings'
    | '/admin/dashboard/settings'
    | '/admin/dashboard/users'
    | '/dashboard'
    | '/admin/dashboard'
    | '/dashboard/quizzes/$id'
    | '/admin/dashboard/course-management/TableData'
    | '/dashboard/my-courses'
    | '/dashboard/quizzes'
    | '/admin/dashboard/course-management'
    | '/admin/dashboard/quizzes-management'
    | '/dashboard/my-courses/$id'
    | '/admin/dashboard/course-management/new-course-lec'
    | '/admin/dashboard/course-management/new-course'
    | '/admin/dashboard/course-management/preview-courses'
    | '/admin/dashboard/quizzes-management/new-quiz-lec'
    | '/admin/dashboard/quizzes-management/new-quiz'
    | '/admin/dashboard/quizzes-management/preview'
    | '/dashboard/my-courses/$id/learn/lecture/$lectureid'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/checkout'
    | '/pricing'
    | '/(userDashboard)'
    | '/(userDashboard)/_dashboardLayout'
    | '/_auth/login'
    | '/_auth/signup'
    | '/admin'
    | '/admin/_auth'
    | '/admin/_dashboardLayout'
    | '/courses/$course'
    | '/courses/'
    | '/admin/_auth/login'
    | '/admin/_auth/signup'
    | '/(userDashboard)/_dashboardLayout/dashboard/leaderboard'
    | '/(userDashboard)/_dashboardLayout/dashboard/mentor'
    | '/(userDashboard)/_dashboardLayout/dashboard/notifications'
    | '/(userDashboard)/_dashboardLayout/dashboard/profile'
    | '/(userDashboard)/_dashboardLayout/dashboard/search'
    | '/(userDashboard)/_dashboardLayout/dashboard/settings'
    | '/admin/_dashboardLayout/dashboard/settings'
    | '/admin/_dashboardLayout/dashboard/users'
    | '/(userDashboard)/_dashboardLayout/dashboard/'
    | '/admin/_dashboardLayout/dashboard/'
    | '/(userDashboard)/_dashboardLayout/dashboard/quizzes/$id'
    | '/admin/_dashboardLayout/dashboard/course-management/TableData'
    | '/(userDashboard)/_dashboardLayout/dashboard/my-courses/'
    | '/(userDashboard)/_dashboardLayout/dashboard/quizzes/'
    | '/admin/_dashboardLayout/dashboard/course-management/'
    | '/admin/_dashboardLayout/dashboard/quizzes-management/'
    | '/(userDashboard)/_dashboardLayout/dashboard/my-courses/$id/'
    | '/admin/_dashboardLayout/dashboard/course-management/new-course-lec/'
    | '/admin/_dashboardLayout/dashboard/course-management/new-course/'
    | '/admin/_dashboardLayout/dashboard/course-management/preview-courses/'
    | '/admin/_dashboardLayout/dashboard/quizzes-management/new-quiz-lec/'
    | '/admin/_dashboardLayout/dashboard/quizzes-management/new-quiz/'
    | '/admin/_dashboardLayout/dashboard/quizzes-management/preview/'
    | '/(userDashboard)/_dashboardLayout/dashboard/my-courses/$id/learn/lecture/$lectureid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AuthRoute: typeof AuthRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  PricingRoute: typeof PricingRoute
  userDashboardRoute: typeof userDashboardRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CoursesCourseRoute: typeof CoursesCourseRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(userDashboard)': {
      id: '/(userDashboard)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof userDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$course': {
      id: '/courses/$course'
      path: '/courses/$course'
      fullPath: '/courses/$course'
      preLoaderRoute: typeof CoursesCourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_dashboardLayout': {
      id: '/admin/_dashboardLayout'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminDashboardLayoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_auth': {
      id: '/admin/_auth'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/(userDashboard)/_dashboardLayout': {
      id: '/(userDashboard)/_dashboardLayout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof userDashboardDashboardLayoutRouteImport
      parentRoute: typeof userDashboardRoute
    }
    '/admin/_auth/signup': {
      id: '/admin/_auth/signup'
      path: '/signup'
      fullPath: '/admin/signup'
      preLoaderRoute: typeof AdminAuthSignupRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/login': {
      id: '/admin/_auth/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminAuthLoginRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_dashboardLayout/dashboard/': {
      id: '/admin/_dashboardLayout/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardLayoutDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/(userDashboard)/_dashboardLayout/dashboard/': {
      id: '/(userDashboard)/_dashboardLayout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof userDashboardDashboardLayoutDashboardIndexRouteImport
      parentRoute: typeof userDashboardDashboardLayoutRoute
    }
    '/admin/_dashboardLayout/dashboard/users': {
      id: '/admin/_dashboardLayout/dashboard/users'
      path: '/dashboard/users'
      fullPath: '/admin/dashboard/users'
      preLoaderRoute: typeof AdminDashboardLayoutDashboardUsersRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/admin/_dashboardLayout/dashboard/settings': {
      id: '/admin/_dashboardLayout/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/admin/dashboard/settings'
      preLoaderRoute: typeof AdminDashboardLayoutDashboardSettingsRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/(userDashboard)/_dashboardLayout/dashboard/settings': {
      id: '/(userDashboard)/_dashboardLayout/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof userDashboardDashboardLayoutDashboardSettingsRouteImport
      parentRoute: typeof userDashboardDashboardLayoutRoute
    }
    '/(userDashboard)/_dashboardLayout/dashboard/search': {
      id: '/(userDashboard)/_dashboardLayout/dashboard/search'
      path: '/dashboard/search'
      fullPath: '/dashboard/search'
      preLoaderRoute: typeof userDashboardDashboardLayoutDashboardSearchRouteImport
      parentRoute: typeof userDashboardDashboardLayoutRoute
    }
    '/(userDashboard)/_dashboardLayout/dashboard/profile': {
      id: '/(userDashboard)/_dashboardLayout/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof userDashboardDashboardLayoutDashboardProfileRouteImport
      parentRoute: typeof userDashboardDashboardLayoutRoute
    }
    '/(userDashboard)/_dashboardLayout/dashboard/notifications': {
      id: '/(userDashboard)/_dashboardLayout/dashboard/notifications'
      path: '/dashboard/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof userDashboardDashboardLayoutDashboardNotificationsRouteImport
      parentRoute: typeof userDashboardDashboardLayoutRoute
    }
    '/(userDashboard)/_dashboardLayout/dashboard/mentor': {
      id: '/(userDashboard)/_dashboardLayout/dashboard/mentor'
      path: '/dashboard/mentor'
      fullPath: '/dashboard/mentor'
      preLoaderRoute: typeof userDashboardDashboardLayoutDashboardMentorRouteImport
      parentRoute: typeof userDashboardDashboardLayoutRoute
    }
    '/(userDashboard)/_dashboardLayout/dashboard/leaderboard': {
      id: '/(userDashboard)/_dashboardLayout/dashboard/leaderboard'
      path: '/dashboard/leaderboard'
      fullPath: '/dashboard/leaderboard'
      preLoaderRoute: typeof userDashboardDashboardLayoutDashboardLeaderboardRouteImport
      parentRoute: typeof userDashboardDashboardLayoutRoute
    }
    '/admin/_dashboardLayout/dashboard/quizzes-management/': {
      id: '/admin/_dashboardLayout/dashboard/quizzes-management/'
      path: '/dashboard/quizzes-management'
      fullPath: '/admin/dashboard/quizzes-management'
      preLoaderRoute: typeof AdminDashboardLayoutDashboardQuizzesManagementIndexRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/admin/_dashboardLayout/dashboard/course-management/': {
      id: '/admin/_dashboardLayout/dashboard/course-management/'
      path: '/dashboard/course-management'
      fullPath: '/admin/dashboard/course-management'
      preLoaderRoute: typeof AdminDashboardLayoutDashboardCourseManagementIndexRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/(userDashboard)/_dashboardLayout/dashboard/quizzes/': {
      id: '/(userDashboard)/_dashboardLayout/dashboard/quizzes/'
      path: '/dashboard/quizzes'
      fullPath: '/dashboard/quizzes'
      preLoaderRoute: typeof userDashboardDashboardLayoutDashboardQuizzesIndexRouteImport
      parentRoute: typeof userDashboardDashboardLayoutRoute
    }
    '/(userDashboard)/_dashboardLayout/dashboard/my-courses/': {
      id: '/(userDashboard)/_dashboardLayout/dashboard/my-courses/'
      path: '/dashboard/my-courses'
      fullPath: '/dashboard/my-courses'
      preLoaderRoute: typeof userDashboardDashboardLayoutDashboardMyCoursesIndexRouteImport
      parentRoute: typeof userDashboardDashboardLayoutRoute
    }
    '/admin/_dashboardLayout/dashboard/course-management/TableData': {
      id: '/admin/_dashboardLayout/dashboard/course-management/TableData'
      path: '/dashboard/course-management/TableData'
      fullPath: '/admin/dashboard/course-management/TableData'
      preLoaderRoute: typeof AdminDashboardLayoutDashboardCourseManagementTableDataRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/(userDashboard)/_dashboardLayout/dashboard/quizzes/$id': {
      id: '/(userDashboard)/_dashboardLayout/dashboard/quizzes/$id'
      path: '/dashboard/quizzes/$id'
      fullPath: '/dashboard/quizzes/$id'
      preLoaderRoute: typeof userDashboardDashboardLayoutDashboardQuizzesIdRouteImport
      parentRoute: typeof userDashboardDashboardLayoutRoute
    }
    '/admin/_dashboardLayout/dashboard/quizzes-management/preview/': {
      id: '/admin/_dashboardLayout/dashboard/quizzes-management/preview/'
      path: '/dashboard/quizzes-management/preview'
      fullPath: '/admin/dashboard/quizzes-management/preview'
      preLoaderRoute: typeof AdminDashboardLayoutDashboardQuizzesManagementPreviewIndexRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/admin/_dashboardLayout/dashboard/quizzes-management/new-quiz/': {
      id: '/admin/_dashboardLayout/dashboard/quizzes-management/new-quiz/'
      path: '/dashboard/quizzes-management/new-quiz'
      fullPath: '/admin/dashboard/quizzes-management/new-quiz'
      preLoaderRoute: typeof AdminDashboardLayoutDashboardQuizzesManagementNewQuizIndexRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/admin/_dashboardLayout/dashboard/quizzes-management/new-quiz-lec/': {
      id: '/admin/_dashboardLayout/dashboard/quizzes-management/new-quiz-lec/'
      path: '/dashboard/quizzes-management/new-quiz-lec'
      fullPath: '/admin/dashboard/quizzes-management/new-quiz-lec'
      preLoaderRoute: typeof AdminDashboardLayoutDashboardQuizzesManagementNewQuizLecIndexRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/admin/_dashboardLayout/dashboard/course-management/preview-courses/': {
      id: '/admin/_dashboardLayout/dashboard/course-management/preview-courses/'
      path: '/dashboard/course-management/preview-courses'
      fullPath: '/admin/dashboard/course-management/preview-courses'
      preLoaderRoute: typeof AdminDashboardLayoutDashboardCourseManagementPreviewCoursesIndexRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/admin/_dashboardLayout/dashboard/course-management/new-course/': {
      id: '/admin/_dashboardLayout/dashboard/course-management/new-course/'
      path: '/dashboard/course-management/new-course'
      fullPath: '/admin/dashboard/course-management/new-course'
      preLoaderRoute: typeof AdminDashboardLayoutDashboardCourseManagementNewCourseIndexRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/admin/_dashboardLayout/dashboard/course-management/new-course-lec/': {
      id: '/admin/_dashboardLayout/dashboard/course-management/new-course-lec/'
      path: '/dashboard/course-management/new-course-lec'
      fullPath: '/admin/dashboard/course-management/new-course-lec'
      preLoaderRoute: typeof AdminDashboardLayoutDashboardCourseManagementNewCourseLecIndexRouteImport
      parentRoute: typeof AdminDashboardLayoutRoute
    }
    '/(userDashboard)/_dashboardLayout/dashboard/my-courses/$id/': {
      id: '/(userDashboard)/_dashboardLayout/dashboard/my-courses/$id/'
      path: '/dashboard/my-courses/$id'
      fullPath: '/dashboard/my-courses/$id'
      preLoaderRoute: typeof userDashboardDashboardLayoutDashboardMyCoursesIdIndexRouteImport
      parentRoute: typeof userDashboardDashboardLayoutRoute
    }
    '/(userDashboard)/_dashboardLayout/dashboard/my-courses/$id/learn/lecture/$lectureid': {
      id: '/(userDashboard)/_dashboardLayout/dashboard/my-courses/$id/learn/lecture/$lectureid'
      path: '/dashboard/my-courses/$id/learn/lecture/$lectureid'
      fullPath: '/dashboard/my-courses/$id/learn/lecture/$lectureid'
      preLoaderRoute: typeof userDashboardDashboardLayoutDashboardMyCoursesIdLearnLectureLectureidRouteImport
      parentRoute: typeof userDashboardDashboardLayoutRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface userDashboardDashboardLayoutRouteChildren {
  userDashboardDashboardLayoutDashboardLeaderboardRoute: typeof userDashboardDashboardLayoutDashboardLeaderboardRoute
  userDashboardDashboardLayoutDashboardMentorRoute: typeof userDashboardDashboardLayoutDashboardMentorRoute
  userDashboardDashboardLayoutDashboardNotificationsRoute: typeof userDashboardDashboardLayoutDashboardNotificationsRoute
  userDashboardDashboardLayoutDashboardProfileRoute: typeof userDashboardDashboardLayoutDashboardProfileRoute
  userDashboardDashboardLayoutDashboardSearchRoute: typeof userDashboardDashboardLayoutDashboardSearchRoute
  userDashboardDashboardLayoutDashboardSettingsRoute: typeof userDashboardDashboardLayoutDashboardSettingsRoute
  userDashboardDashboardLayoutDashboardIndexRoute: typeof userDashboardDashboardLayoutDashboardIndexRoute
  userDashboardDashboardLayoutDashboardQuizzesIdRoute: typeof userDashboardDashboardLayoutDashboardQuizzesIdRoute
  userDashboardDashboardLayoutDashboardMyCoursesIndexRoute: typeof userDashboardDashboardLayoutDashboardMyCoursesIndexRoute
  userDashboardDashboardLayoutDashboardQuizzesIndexRoute: typeof userDashboardDashboardLayoutDashboardQuizzesIndexRoute
  userDashboardDashboardLayoutDashboardMyCoursesIdIndexRoute: typeof userDashboardDashboardLayoutDashboardMyCoursesIdIndexRoute
  userDashboardDashboardLayoutDashboardMyCoursesIdLearnLectureLectureidRoute: typeof userDashboardDashboardLayoutDashboardMyCoursesIdLearnLectureLectureidRoute
}

const userDashboardDashboardLayoutRouteChildren: userDashboardDashboardLayoutRouteChildren =
  {
    userDashboardDashboardLayoutDashboardLeaderboardRoute:
      userDashboardDashboardLayoutDashboardLeaderboardRoute,
    userDashboardDashboardLayoutDashboardMentorRoute:
      userDashboardDashboardLayoutDashboardMentorRoute,
    userDashboardDashboardLayoutDashboardNotificationsRoute:
      userDashboardDashboardLayoutDashboardNotificationsRoute,
    userDashboardDashboardLayoutDashboardProfileRoute:
      userDashboardDashboardLayoutDashboardProfileRoute,
    userDashboardDashboardLayoutDashboardSearchRoute:
      userDashboardDashboardLayoutDashboardSearchRoute,
    userDashboardDashboardLayoutDashboardSettingsRoute:
      userDashboardDashboardLayoutDashboardSettingsRoute,
    userDashboardDashboardLayoutDashboardIndexRoute:
      userDashboardDashboardLayoutDashboardIndexRoute,
    userDashboardDashboardLayoutDashboardQuizzesIdRoute:
      userDashboardDashboardLayoutDashboardQuizzesIdRoute,
    userDashboardDashboardLayoutDashboardMyCoursesIndexRoute:
      userDashboardDashboardLayoutDashboardMyCoursesIndexRoute,
    userDashboardDashboardLayoutDashboardQuizzesIndexRoute:
      userDashboardDashboardLayoutDashboardQuizzesIndexRoute,
    userDashboardDashboardLayoutDashboardMyCoursesIdIndexRoute:
      userDashboardDashboardLayoutDashboardMyCoursesIdIndexRoute,
    userDashboardDashboardLayoutDashboardMyCoursesIdLearnLectureLectureidRoute:
      userDashboardDashboardLayoutDashboardMyCoursesIdLearnLectureLectureidRoute,
  }

const userDashboardDashboardLayoutRouteWithChildren =
  userDashboardDashboardLayoutRoute._addFileChildren(
    userDashboardDashboardLayoutRouteChildren,
  )

interface userDashboardRouteChildren {
  userDashboardDashboardLayoutRoute: typeof userDashboardDashboardLayoutRouteWithChildren
}

const userDashboardRouteChildren: userDashboardRouteChildren = {
  userDashboardDashboardLayoutRoute:
    userDashboardDashboardLayoutRouteWithChildren,
}

const userDashboardRouteWithChildren = userDashboardRoute._addFileChildren(
  userDashboardRouteChildren,
)

interface AdminAuthRouteChildren {
  AdminAuthLoginRoute: typeof AdminAuthLoginRoute
  AdminAuthSignupRoute: typeof AdminAuthSignupRoute
}

const AdminAuthRouteChildren: AdminAuthRouteChildren = {
  AdminAuthLoginRoute: AdminAuthLoginRoute,
  AdminAuthSignupRoute: AdminAuthSignupRoute,
}

const AdminAuthRouteWithChildren = AdminAuthRoute._addFileChildren(
  AdminAuthRouteChildren,
)

interface AdminDashboardLayoutRouteChildren {
  AdminDashboardLayoutDashboardSettingsRoute: typeof AdminDashboardLayoutDashboardSettingsRoute
  AdminDashboardLayoutDashboardUsersRoute: typeof AdminDashboardLayoutDashboardUsersRoute
  AdminDashboardLayoutDashboardIndexRoute: typeof AdminDashboardLayoutDashboardIndexRoute
  AdminDashboardLayoutDashboardCourseManagementTableDataRoute: typeof AdminDashboardLayoutDashboardCourseManagementTableDataRoute
  AdminDashboardLayoutDashboardCourseManagementIndexRoute: typeof AdminDashboardLayoutDashboardCourseManagementIndexRoute
  AdminDashboardLayoutDashboardQuizzesManagementIndexRoute: typeof AdminDashboardLayoutDashboardQuizzesManagementIndexRoute
  AdminDashboardLayoutDashboardCourseManagementNewCourseLecIndexRoute: typeof AdminDashboardLayoutDashboardCourseManagementNewCourseLecIndexRoute
  AdminDashboardLayoutDashboardCourseManagementNewCourseIndexRoute: typeof AdminDashboardLayoutDashboardCourseManagementNewCourseIndexRoute
  AdminDashboardLayoutDashboardCourseManagementPreviewCoursesIndexRoute: typeof AdminDashboardLayoutDashboardCourseManagementPreviewCoursesIndexRoute
  AdminDashboardLayoutDashboardQuizzesManagementNewQuizLecIndexRoute: typeof AdminDashboardLayoutDashboardQuizzesManagementNewQuizLecIndexRoute
  AdminDashboardLayoutDashboardQuizzesManagementNewQuizIndexRoute: typeof AdminDashboardLayoutDashboardQuizzesManagementNewQuizIndexRoute
  AdminDashboardLayoutDashboardQuizzesManagementPreviewIndexRoute: typeof AdminDashboardLayoutDashboardQuizzesManagementPreviewIndexRoute
}

const AdminDashboardLayoutRouteChildren: AdminDashboardLayoutRouteChildren = {
  AdminDashboardLayoutDashboardSettingsRoute:
    AdminDashboardLayoutDashboardSettingsRoute,
  AdminDashboardLayoutDashboardUsersRoute:
    AdminDashboardLayoutDashboardUsersRoute,
  AdminDashboardLayoutDashboardIndexRoute:
    AdminDashboardLayoutDashboardIndexRoute,
  AdminDashboardLayoutDashboardCourseManagementTableDataRoute:
    AdminDashboardLayoutDashboardCourseManagementTableDataRoute,
  AdminDashboardLayoutDashboardCourseManagementIndexRoute:
    AdminDashboardLayoutDashboardCourseManagementIndexRoute,
  AdminDashboardLayoutDashboardQuizzesManagementIndexRoute:
    AdminDashboardLayoutDashboardQuizzesManagementIndexRoute,
  AdminDashboardLayoutDashboardCourseManagementNewCourseLecIndexRoute:
    AdminDashboardLayoutDashboardCourseManagementNewCourseLecIndexRoute,
  AdminDashboardLayoutDashboardCourseManagementNewCourseIndexRoute:
    AdminDashboardLayoutDashboardCourseManagementNewCourseIndexRoute,
  AdminDashboardLayoutDashboardCourseManagementPreviewCoursesIndexRoute:
    AdminDashboardLayoutDashboardCourseManagementPreviewCoursesIndexRoute,
  AdminDashboardLayoutDashboardQuizzesManagementNewQuizLecIndexRoute:
    AdminDashboardLayoutDashboardQuizzesManagementNewQuizLecIndexRoute,
  AdminDashboardLayoutDashboardQuizzesManagementNewQuizIndexRoute:
    AdminDashboardLayoutDashboardQuizzesManagementNewQuizIndexRoute,
  AdminDashboardLayoutDashboardQuizzesManagementPreviewIndexRoute:
    AdminDashboardLayoutDashboardQuizzesManagementPreviewIndexRoute,
}

const AdminDashboardLayoutRouteWithChildren =
  AdminDashboardLayoutRoute._addFileChildren(AdminDashboardLayoutRouteChildren)

interface AdminRouteChildren {
  AdminAuthRoute: typeof AdminAuthRouteWithChildren
  AdminDashboardLayoutRoute: typeof AdminDashboardLayoutRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuthRoute: AdminAuthRouteWithChildren,
  AdminDashboardLayoutRoute: AdminDashboardLayoutRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AuthRoute: AuthRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  PricingRoute: PricingRoute,
  userDashboardRoute: userDashboardRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CoursesCourseRoute: CoursesCourseRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
